# Permalinks
permalink:        pretty

# Setup
title:            Peter Yoachim
description:      witty byline
tagline:          where I calculate things for fun
url:              http://yoachim.github.io/
paginate:         5
paginate_path:    "/blargh/page:num"
baseurl:          
author:
  name:           Peter Yoachim
  url:            https://twitter.com/PeterYoachim
  email:          pyoachim@gmail.com

