# Permalinks
permalink:        pretty

# Setup
title:            Peter's Blargh
tagline:          where I calculate things for fun
url:              http://yoachim.github.io/
paginate:         5
baseurl:          
author:
  name:           Peter Yoachim
  url:            https://twitter.com/PeterYoachim
  email:          pyoachim@gmail.com

